### Python 버전 확인

In [1]:
!python --version

Python 3.11.5


### [type] int, float, str

In [2]:
a = 1
b = -1
c = 1.3
d = 4.5

In [3]:
print(a, type(a))
print(d, type(d))

1 <class 'int'>
4.5 <class 'float'>


In [4]:
sum_int = a + b
print(sum_int, type(sum_int))

0 <class 'int'>


In [5]:
sum_float = c + d
print(sum_float, type(sum_float))

5.8 <class 'float'>


In [6]:
e = 'deep '
f = 'learning'

In [7]:
print(e, type(e))

deep  <class 'str'>


In [8]:
sum_str = e + f
print(sum_str, type(sum_str))

deep learning <class 'str'>


### [type] bool

In [9]:
g = True
h = False

In [10]:
print(g, type(g))

True <class 'bool'>


In [11]:
sum_bool = g + h
print(sum_bool, type(sum_bool))

1 <class 'int'>


### type 바꾸기

In [12]:
i = 7
j = '7'

In [13]:
print(i, type(i))
print(j, type(j))

7 <class 'int'>
7 <class 'str'>


In [14]:
k = str(i)
l = int(j)

In [15]:
print(k, type(k))
print(l, type(l))

7 <class 'str'>
7 <class 'int'>


### [자료구조] list

In [16]:
m = [1, 2, 3, 4]

In [17]:
print(m, type(m))

[1, 2, 3, 4] <class 'list'>


In [18]:
print(m[0])
print(m[-1])

1
4


In [19]:
print(m[:2])
print(m[1:-1])
print(m[2:])

[1, 2]
[2, 3]
[3, 4]


### [자료구조] tuple

In [20]:
n = (8, 9)
print(n, type(n))

(8, 9) <class 'tuple'>


In [21]:
print(n[1])
print(n[-1])
print(n[0:])

9
9
(8, 9)


### [자료구조] dictionary

In [22]:
o = {'lecture':['probability', 'DL'], 'students':[35, 30]}

In [23]:
print(o, type(o))

{'lecture': ['probability', 'DL'], 'students': [35, 30]} <class 'dict'>


In [24]:
print(o['lecture'])
print(o['students'])

['probability', 'DL']
[35, 30]


In [25]:
print(o['lecture'][1])
print(o['students'][0])

DL
35


In [26]:
o.keys()

dict_keys(['lecture', 'students'])

In [27]:
o.values()

dict_values([['probability', 'DL'], [35, 30]])

### [자료구조] array

In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr, type(arr))

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


In [29]:
p = np.ones(10)
print(p, type(p))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [30]:
q = np.zeros((2, 5))
print(q, type(q))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] <class 'numpy.ndarray'>


### 조건문

In [31]:
r = int(input())

if r == 3:
    print('r = 3')
else:
    print('r != 3')

3
r = 3


In [32]:
s = int(input())

if s == 1:
    print('s = 1')
elif s == 2:
    print('s = 2')
elif s == 3:
    print('s = 3')
else:
    print('Other numbers')

3
s = 3


### 반복문(for)

In [33]:
for t in range(3):
    print(t)

0
1
2


### 반복문(while)

In [34]:
u = 1
while u < 7:
    print(u)
    u += 1

1
2
3
4
5
6


### break문

In [35]:
v = np.random.randint(10, size = 10)
print(v)

[8 4 5 7 4 6 3 7 4 3]


In [36]:
for i in v:
    if i % 2 == 0:
        print(i, '은 짝수입니다.')
        break

8 은 짝수입니다.


### try-except문

In [37]:
x = [1, 2, 'panda', 3]

In [40]:
#에러 예시
# for i in x:
#     y = i ** 2
#     print(y)

In [39]:
for i in x:
    try:
        y = i ** 2
        print(y)
    except:
        print(i, '는 숫자가 아닙니다.')

1
4
panda 는 숫자가 아닙니다.
9
