In [12]:
import numpy as np
from scipy import linalg

In [13]:
A1 = np.array([[1,5,0],[2,4,-1],[0,-2,0]], dtype=np.float64)
A1

array([[ 1.,  5.,  0.],
       [ 2.,  4., -1.],
       [ 0., -2.,  0.]])

In [14]:
A2 = np.array([[1,-4,2],[-2,8,-9],[-1,7,0]], dtype=np.float64)
A2

array([[ 1., -4.,  2.],
       [-2.,  8., -9.],
       [-1.,  7.,  0.]])

In [15]:
# 행렬식 구하기
det1 = linalg.det(A1)
det1

-2.0

In [16]:
det2 = linalg.det(A2)
det2

15.0

In [17]:
A3 = np.array([[1,2,1],[2,1,3],[1,3,1]], dtype=np.float64)
A3

array([[1., 2., 1.],
       [2., 1., 3.],
       [1., 3., 1.]])

In [18]:
inv_A3 = linalg.inv(A3)
inv_A3

array([[ 8., -1., -5.],
       [-1.,  0.,  1.],
       [-5.,  1.,  3.]])

In [19]:
A3 @ inv_A3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Ax = b 풀기

In [20]:
b = np.ones((3,), dtype=np.float64)
A_sing = np.array([[1,3,4],[-4,2,-6],[-3,-2,-7]], dtype=np.float64) # singular matrix
A_gen = np.array([[0,1,2],[1,0,3],[4,-3,8]], dtype=np.float64) # 대상행렬의 속성을 잘 모르는 경우
A_sym = np.array([[1,2,1],[2,1,3],[1,3,1]], dtype=np.float64) # symmetric matrix
A_sym_c = np.array([[1,2-1j,1+2j],[2-1j,1,3],[1+2j,3,1]], dtype=np.complex128) # symmetric complex matrix
A_her = np.array([[1,2+1j,1-2j],[2-1j,1,3],[1+2j,3,1]], dtype=np.complex128) # hermitian matrix
A_pos = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]], dtype=np.float64) # positive definite matrix

In [21]:
#x_sing = linalg.solve(A_sing, b)

In [22]:
x_gen = linalg.solve(A_gen,b)
x_gen

array([ 1.,  1., -0.])

In [23]:
A_gen@x_gen-b

array([0., 0., 0.])

In [24]:
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve.html#scipy.linalg.solve

x_sym = linalg.solve(A_sym, b, assume_a="sym")  
x_sym

array([ 2.,  0., -1.])

In [25]:
print(A_sym@x_sym-b)

[0. 0. 0.]


In [26]:
x_sym_c = linalg.solve(A_sym_c, b, assume_a="sym")
x_sym_c

array([0.00689655+0.11724138j, 0.35172414-0.02068966j,
       0.17241379-0.06896552j])

In [27]:
A_sym_c@x_sym_c-b

array([2.22044605e-16-5.55111512e-17j, 4.44089210e-16-2.77555756e-16j,
       4.44089210e-16+1.38777878e-16j])

In [28]:
A_sym_c@x_sym_c

array([1.-5.55111512e-17j, 1.-2.77555756e-16j, 1.+1.38777878e-16j])

In [29]:
x_her = linalg.solve(A_her, b, assume_a="her")
x_her

array([0.11111111+1.11111111e-01j, 0.33333333-1.11111111e-01j,
       0.11111111+1.11022302e-16j])

In [30]:
A_her@x_her-b

array([ 0.00000000e+00+5.55111512e-17j, -4.44089210e-16+1.94289029e-16j,
        2.22044605e-16-1.66533454e-16j])

In [31]:
A_her@x_her

array([1.+5.55111512e-17j, 1.+1.94289029e-16j, 1.-1.66533454e-16j])

In [32]:
x_pos = linalg.solve(A_pos, b, assume_a="pos")
x_pos

array([1.5, 2. , 1.5])

In [33]:
A_pos@x_pos-b

array([-8.88178420e-16,  1.55431223e-15, -4.44089210e-16])

In [34]:
A_pos@x_pos

array([1., 1., 1.])

In [35]:
zr_3 = np.zeros((3,), dtype=np.float64)
zr_3

array([0., 0., 0.])

In [36]:
bool_close = np.allclose(A_pos@x_pos-b, zr_3)
bool_close

True

### 역행렬 연산 대상행렬 A가 삼각행렬인 경우

In [37]:
A4 = np.array([[1,0,0,0],[1,4,0,0],[5,0,1,0],[8,1,-2,2]],dtype=np.float64) # 행렬 A는 하삼각행렬
b4 = np.array([1,2,3,4],dtype=np.float64)
print('A4 = \n', A4)
print()
print('b4 = \n', b4)

A4 = 
 [[ 1.  0.  0.  0.]
 [ 1.  4.  0.  0.]
 [ 5.  0.  1.  0.]
 [ 8.  1. -2.  2.]]

b4 = 
 [1. 2. 3. 4.]


In [38]:
x4 = linalg.solve_triangular(A4, b4, lower=True) # default option은 lower=False
x4

array([ 1.   ,  0.25 , -2.   , -4.125])

In [39]:
A4@x4

array([1., 2., 3., 4.])

In [40]:
zr_4 = np.zeros((4,), dtype=np.float64)
zr_4

array([0., 0., 0., 0.])

In [41]:
bool_close = np.allclose(A4@x4-b4, zr_4)
bool_close

True

### 삼각행렬: 상삼각행렬, 하삼각행렬

In [42]:
E = np.random.randint(1, 10, 9).reshape(3, 3)
E

array([[5, 5, 1],
       [8, 2, 1],
       [9, 7, 5]])

### 상삼각행렬

In [43]:
np.triu(E)

array([[5, 5, 1],
       [0, 2, 1],
       [0, 0, 5]])

In [44]:
np.triu(E, k=0)

array([[5, 5, 1],
       [0, 2, 1],
       [0, 0, 5]])

In [45]:
np.triu(E, k=1)

array([[0, 5, 1],
       [0, 0, 1],
       [0, 0, 0]])

In [46]:
np.triu(E, k=2)

array([[0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

### 하삼각행렬

In [47]:
np.tril(E)

array([[5, 0, 0],
       [8, 2, 0],
       [9, 7, 5]])

In [48]:
np.tril(E, k=0)

array([[5, 0, 0],
       [8, 2, 0],
       [9, 7, 5]])

In [49]:
np.tril(E, k=1)

array([[5, 5, 0],
       [8, 2, 1],
       [9, 7, 5]])

In [50]:
np.tril(E, k=-1)

array([[0, 0, 0],
       [8, 0, 0],
       [9, 7, 0]])

### LU 분해: A = PLU 여기서 P: 치환행렬(permutation matrix), L: 대각원소가 1인 하삼각행렬, U: 상삼각행렬

In [51]:
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu.html
# http://elearning.kocw.net/contents4/document/lec/2013/Chungbuk/LeeGeonmyeong1/7.pdf

A5 = np.array([[2,4,-1,5,-2],[-4,-5,3,-8,1],[2,-5,-4,1,8],[-6,0,7,-3,1]], dtype=np.float64)
print('A5 = \n', A5)

A5 = 
 [[ 2.  4. -1.  5. -2.]
 [-4. -5.  3. -8.  1.]
 [ 2. -5. -4.  1.  8.]
 [-6.  0.  7. -3.  1.]]


In [52]:
P, L, U = linalg.lu(A5)

print('L = \n', L)
print()
print('U = \n', U)

L = 
 [[ 1.          0.          0.          0.        ]
 [ 0.66666667  1.          0.          0.        ]
 [-0.33333333  1.          1.          0.        ]
 [-0.33333333 -0.8         0.13333333  1.        ]]

U = 
 [[-6.00000000e+00  0.00000000e+00  7.00000000e+00 -3.00000000e+00
   1.00000000e+00]
 [ 0.00000000e+00 -5.00000000e+00 -1.66666667e+00 -6.00000000e+00
   3.33333333e-01]
 [ 0.00000000e+00  0.00000000e+00 -2.22044605e-16  6.00000000e+00
   8.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.60000000e+00
  -2.46666667e+00]]


In [53]:
print('A5 = \n', A5)
print()
print('LU = \n', L@U)

A5 = 
 [[ 2.  4. -1.  5. -2.]
 [-4. -5.  3. -8.  1.]
 [ 2. -5. -4.  1.  8.]
 [-6.  0.  7. -3.  1.]]

LU = 
 [[-6.  0.  7. -3.  1.]
 [-4. -5.  3. -8.  1.]
 [ 2. -5. -4.  1.  8.]
 [ 2.  4. -1.  5. -2.]]


In [54]:
print('P = \n', P)
print()
print('PLU = \n', P@L@U)
print()
print('A5 = \n', A5)

P = 
 [[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]

PLU = 
 [[ 2.  4. -1.  5. -2.]
 [-4. -5.  3. -8.  1.]
 [ 2. -5. -4.  1.  8.]
 [-6.  0.  7. -3.  1.]]

A5 = 
 [[ 2.  4. -1.  5. -2.]
 [-4. -5.  3. -8.  1.]
 [ 2. -5. -4.  1.  8.]
 [-6.  0.  7. -3.  1.]]


In [55]:
A6 = np.array([[7,5,6,6],[1,2,2,8],[5,4,4,8],[9,5,8,7]], dtype=np.float64)
print('A6 = \n', A6)

A6 = 
 [[7. 5. 6. 6.]
 [1. 2. 2. 8.]
 [5. 4. 4. 8.]
 [9. 5. 8. 7.]]


In [56]:
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu_factor.html

lu, piv = linalg.lu_factor(A6)
print('lu = \n', lu)

lu = 
 [[ 9.          5.          8.          7.        ]
 [ 0.11111111  1.44444444  1.11111111  7.22222222]
 [ 0.55555556  0.84615385 -1.38461538 -2.        ]
 [ 0.77777778  0.76923077  0.77777778 -3.44444444]]


In [57]:
L = np.tril(lu, k=-1) + np.identity(4)
print('L = \n' ,L)

L = 
 [[1.         0.         0.         0.        ]
 [0.11111111 1.         0.         0.        ]
 [0.55555556 0.84615385 1.         0.        ]
 [0.77777778 0.76923077 0.77777778 1.        ]]


In [58]:
U = np.triu(lu)
print('U = \n', U)

U = 
 [[ 9.          5.          8.          7.        ]
 [ 0.          1.44444444  1.11111111  7.22222222]
 [ 0.          0.         -1.38461538 -2.        ]
 [ 0.          0.          0.         -3.44444444]]


In [59]:
print('A6 = \n', A6)

A6 = 
 [[7. 5. 6. 6.]
 [1. 2. 2. 8.]
 [5. 4. 4. 8.]
 [9. 5. 8. 7.]]


In [60]:
print('LU = \n', L@U)

LU = 
 [[9. 5. 8. 7.]
 [1. 2. 2. 8.]
 [5. 4. 4. 8.]
 [7. 5. 6. 6.]]


In [61]:
print('piv = \n', piv)

piv = 
 [3 1 2 3]


### Ax=b 풀기

In [62]:
b6 = np.ones((4,), dtype=np.float64)
print('b6 = \n', b6)

b6 = 
 [1. 1. 1. 1.]


In [63]:
x6 = linalg.lu_solve((lu,piv), b6)
print('x6 = \n', x6)

x6 = 
 [-0.16129032  0.19354839  0.12903226  0.06451613]


In [64]:
print(np.allclose(A6@x6, b6))

True


## 고유값, 고유벡터

In [65]:
A = np.array([[4, 2],[3, 5]], dtype=np.float64)

print('A = \n', A)

A = 
 [[4. 2.]
 [3. 5.]]


In [66]:
eigvals, eigvecs = linalg.eig(A)
print('eigen values = \n', eigvals)
print()
print('eigen vectors = \n', eigvecs)

eigen values = 
 [2.+0.j 7.+0.j]

eigen vectors = 
 [[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


In [67]:
v1 = eigvecs[:,0]
n_v1 = linalg.norm(v1)

print(n_v1)

0.9999999999999999


In [68]:
print(np.allclose(1, n_v1))

True


In [69]:
comp1 = A @ eigvecs
comp2 = eigvecs * eigvals

print(np.allclose(comp1, comp2))

True
